### ISSUE TITLE
README should reflect new location

### ISSUE THREAD

**Issue by karenetheridge** [drazisil/ghi#10]
The readme still references `https://raw.githubusercontent.com/stephencelis/ghi/master/ghi` -- this should be updated with the new URL.

**Comment by drazisil** [comment]
Thanks @karenetheridge . Can you create a PR and I would be happy to merge?

**Comment by karenetheridge** [comment]
What is the correct location? The README says ghi is now maintained by Alex Chesters, but that's not you and this isn't his repo.

**Comment by drazisil** [comment]
Sorry @karenetheridge, I should merge this fix soon, waiting on the tests to pass. :)

**Comment by pataquets** [comment]
@drazisil : FYI: also updated upstream project readme at stephencelis/ghi#395. However, no new releases/tags have been made (on Github  releases), so readme's `curl` downloads same binary.

**Comment by drazisil** [comment]
@pataquets Thanks for the ping. https://github.com/drazisil/ghi/releases/tag/1.2.1 should handle that. :crossed_fingers:

**Comment by pataquets** [comment]
Downloaded and installed. Will report, if anything arises. Thank you!
