### ISSUE TITLE
error: For 'properties/issue', "517" is not an integer.

### ISSUE THREAD

**Issue by karenetheridge** [drazisil/ghi#11]
see https://github.com/stephencelis/ghi/issues/371

**Comment by drazisil** [comment]
I'm not very good at Ruby. I'll take a look, but PRs welcome. The issue is that all args are strings, and somewhere it is being assumed to be a number.

**Comment by Farmerjoe12** [comment]
Hey @karenetheridge , I can't seem to reproduce your bug. It doesn't seem like this is still an issue? I ran the same commands on the same repo and didn't get the 'properties/issue' bug.

**Comment by karenetheridge** [comment]
I see the same problem still:

```
: [ether@aquavit git/conch]$; brew upgrade ghi
Error: ghi 1.2.0_4 already installed
: [ether@aquavit git/conch]$; ghi -V
ghi version 1.2.0
: [ether@aquavit git/conch]$; ghi edit 517 -H
Invalid request.

For 'properties/issue', "517" is not an integer.
```

**Comment by Farmerjoe12** [comment]
You’re using a Mac?


Sent from Yahoo Mail for iPhone


On Thursday, July 18, 2019, 3:17 PM, Karen Etheridge <notifications@github.com> wrote:


I see the same problem still:
: [ether@aquavit git/conch]$; brew upgrade ghi
Error: ghi 1.2.0_4 already installed
: [ether@aquavit git/conch]$; ghi -V
ghi version 1.2.0
: [ether@aquavit git/conch]$; ghi edit 517 -H
Invalid request.

For 'properties/issue', "517" is not an integer.

**Comment by karenetheridge** [comment]
yes, using OSX.

**Comment by Farmerjoe12** [comment]
Is this only happening when you use 'edit'? What about comment, update, show, open, close, and assign?

**Comment by karenetheridge** [comment]
create, open, close, comment, lock and unlock all work ok.  `ghi edit 'new title'` also works.
