### ISSUE TITLE
Is there a way to search through the issues and the messages in ghi

### ISSUE THREAD

**Issue by alphaCTzo7G** [drazisil/ghi#7]
@drazisil , 

I noticed that you are maintaining the ghi plugin.. Thanks for keeping this up. This is amazing.

I frequently need to search through the titles and comments of various issues. Is there a way to search through the issues for specific keywords in the `ghi` plugin?

**Comment by alphaCTzo7G** [comment]
Well, I just made a small shell script: `for ((i = 1; i<100; i++)); ghi show $i | grep "log"` to search through it..

**Comment by nichtich** [comment]
Better retrieve the exact number of issues:

    $ expr $(ghi list | wc -l) - 1

Or use option `--verbose` to emit the full issue text:

    $ ghi list --verbose | grep "log"

This will only emit lines instead of issue numbers, so a more elaborated command may be more useful.

**Comment by Farmerjoe12** [comment]
Can this be closed?

**Comment by drazisil** [comment]
@alphaCTzo7G Are you ok with https://github.com/drazisil/ghi/settings#issuecomment-427750626 as a workround?
